### ISSUE TITLE
期刊标签

### ISSUE THREAD

**Issue by ME7O522** [MuiseDestiny/zotero-connected-papers#1]
大佬，期刊标签那里用的是哪个插件呀？

**Comment by northword** [comment]
> 大佬，期刊标签那里用的是哪个插件呀？

[zotero-style](https://github.com/MuiseDestiny/zotero-style)

**Comment by ME7O522** [comment]
谢谢！

> > 大佬，期刊标签那里用的是哪个插件呀？
> 
> [zotero-style](https://github.com/MuiseDestiny/zotero-style)
