### ISSUE TITLE
大佬，请问下这个适配 7 了吗？想入手，求大大回复。

### ISSUE THREAD

**Issue by Zhangxigu** [MuiseDestiny/zotero-connected-papers#10]

**Comment by MuiseDestiny** [comment]
是的，readme连接可已加入内测

**Comment by Zhangxigu** [comment]
好的，感谢！还有个问题就是，用了这个会有每个月五篇文献的限制吗？connected paper那里我没有开会员。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Polygon ***@***.***&gt;
发送时间: 2023年8月17日 19:58
收件人: MuiseDestiny/zotero-connected-papers ***@***.***&gt;
抄送: Zhangxigu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MuiseDestiny/zotero-connected-papers] 大佬，请问下这个适配 7 了吗？想入手，求大大回复。 (Issue #10)





 
是的，readme连接可已加入内测

**Comment by MuiseDestiny** [comment]
> 好的，感谢！还有个问题就是，用了这个会有每个月五篇文献的限制吗？connected paper那里我没有开会员。 发自我的iPhone
> […](#)

无

**Comment by Zhangxigu** [comment]
感谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Polygon ***@***.***&gt;
发送时间: 2023年8月17日 20:35
收件人: MuiseDestiny/zotero-connected-papers ***@***.***&gt;
抄送: Zhangxigu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MuiseDestiny/zotero-connected-papers] 大佬，请问下这个适配 7 了吗？想入手，求大大回复。 (Issue #10)





  
好的，感谢！还有个问题就是，用了这个会有每个月五篇文献的限制吗？connected paper那里我没有开会员。 发自我的iPhone
 …
  
无
