### ISSUE TITLE
The password for uncompressing connected-papers .rar file

### ISSUE THREAD

**Issue by franciszchen** [MuiseDestiny/zotero-connected-papers#2]
Thanks for sharing the project. I downloaded the zotero-reference.rar file, but found the password is required to uncompress the .rar file. How to solve this problem? Thx~

<img width="404" alt="image" src="https://user-images.githubusercontent.com/16402098/234579694-9011b84e-436f-479e-8c5e-7ef42f8cd2ff.png">

**Comment by MuiseDestiny** [comment]
I’m sorry, this repository is used to contact the Connected Papers official team. The plugin is still under development and is not yet available.

**Comment by franciszchen** [comment]
Understood. This project is cool. Looking forward to your updates!
