### ISSUE TITLE
啥时候开源(可用)?

### ISSUE THREAD

**Issue by dualer** [MuiseDestiny/zotero-connected-papers#9]
RT

**Comment by MuiseDestiny** [comment]
https://mall.bilibili.com/neul-next/index.html?page=mall-up_itemDetail&noTitleBar=1&itemsId=1103216038&from=items_share&msource=items_share

可以付费加入内测

**Comment by LatinaXu** [comment]
> https://mall.bilibili.com/neul-next/index.html?page=mall-up_itemDetail&noTitleBar=1&itemsId=1103216038&from=items_share&msource=items_share
> 
> 可以付费加入内测
链接失效了，显示商品下架

**Comment by MuiseDestiny** [comment]
https://gitee.com/MuiseDestiny/plugins
